### ISSUE TITLE
Add message during login and unlock

### ISSUE THREAD

**Issue by beguene** [hirosystems/stacks-wallet-web#2062]
A message should be displayed during login and unlock (above the password field) to indicate to the user that the login/unlock time can take up to 40 seconds.
This would help reduce complains from users who maybe have less performant computer. They would at least be aware that such a long waiting time can be expected.

**Comment by kyranjamie** [comment]
Big +1 to this. Loads of things we can do here, a message is a good start.

I wonder if it'd have more user-distracting affect appearing a few seconds into the duration, rather than right away. What do you think? Perhaps a different message that appears only if it takes the extreme times of 20s+? 🤔 

cc @eugeniadigon any fun ideas how we might improve the perceived speed of the unlock time? Satoshi quotes? Snake game? Stats about the blockchain? 🧠

**Comment by ginny-d** [comment]
I'd advise against adding a fixed message that always says "20+ / 40+ seconds to log in" even before the user logged in - it sounds quite discouraging, even more if it's not the general rule

I like more the idea of leaving as is, but when the wallet detects it's taking more than let's say 5 seconds, that's when we display a "We're fetching your data, login can take a while" (or something like that) and then it starts swapping that message for some random / interesting facts and stats. Some examples
- It's been ### days since Satoshi's last message to the world
- Bitcoin price went up % in the last 24hs
- There's ### apps in the Stacks ecosystem you can interact with
Even memes or easter-eggs 

I'd also advice against anything related to a game because anyway 40 seconds it's not *that* much of a time for the user to perform an action/play something

**Comment by kyranjamie** [comment]
Wasn't entirely serious about a snake game. Agree we shouldn't mention times, we can't predict these. 40s case shouldn't ever happen, something is wrong if so. It should take no more than ~3–6s.

Encourage you to experiment with these ideas Beguene, would love to see some in action.

**Comment by beguene** [comment]
@kyranjamie @eugeniadigon Thanks a lot for the feedback !  Those are great ideas. 
I will implement this dynamic message display you suggested @kyranjamie with the copy of @eugeniadigon. It will also be configurable. We can experiment with that.

**Comment by andresgalante** [comment]
Is this issue in development?

**Comment by beguene** [comment]
@timstackblock @Eshwari007 I intentionally added a delay during login and unlock so you can see the messages. It will always take at least 30 seconds

**Comment by timstackblock** [comment]
@kyranjamie @beguene I am getting a white screen when trying to use this wallet on stacks art lets make sure we regression test with normal lock unlock times.
